# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VanBanDOJI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VanBanDOJI
  pod 'Firebase/Messaging'
  target 'VanBanDOJI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VanBanDOJITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'VanBanDOJI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VanBanDOJI-tvOS

  # target 'VanBanDOJI-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
